[build]
  publish = "/"
  command = ""

[dev]
  publish = "/"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
